// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-1HJZlt3f3TJ0NOGC8GgkjakirNyDvVU',
    appId: '1:314140607658:web:7c01690b4539af3bfc7cd3',
    messagingSenderId: '314140607658',
    projectId: 'music-app-2f59f',
    authDomain: 'music-app-2f59f.firebaseapp.com',
    storageBucket: 'music-app-2f59f.firebasestorage.app',
    measurementId: 'G-TTHZGXMLPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvpfop44kJqFmYoJ9Jf8XBYb_Qlj4x4QA',
    appId: '1:314140607658:android:07b21ec032071ea5fc7cd3',
    messagingSenderId: '314140607658',
    projectId: 'music-app-2f59f',
    storageBucket: 'music-app-2f59f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWwlXs9Bp-ZQFO3erfLpRVkBj9ndsDltA',
    appId: '1:314140607658:ios:7617cd5357e027bdfc7cd3',
    messagingSenderId: '314140607658',
    projectId: 'music-app-2f59f',
    storageBucket: 'music-app-2f59f.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWwlXs9Bp-ZQFO3erfLpRVkBj9ndsDltA',
    appId: '1:314140607658:ios:7617cd5357e027bdfc7cd3',
    messagingSenderId: '314140607658',
    projectId: 'music-app-2f59f',
    storageBucket: 'music-app-2f59f.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-1HJZlt3f3TJ0NOGC8GgkjakirNyDvVU',
    appId: '1:314140607658:web:9f04245229a86842fc7cd3',
    messagingSenderId: '314140607658',
    projectId: 'music-app-2f59f',
    authDomain: 'music-app-2f59f.firebaseapp.com',
    storageBucket: 'music-app-2f59f.firebasestorage.app',
    measurementId: 'G-BT0QBJJZK8',
  );
}
